### ISSUE TITLE
UFITS Summarize

### ISSUE THREAD

**Issue by MycoMap** [nextgenusfs/amptk#17]
A couple of issues I ran into with ufits summarize:

```
srussell@ubuntu:~/Data/MillerWoods/UFITS$ ufits summarize -i out.otu_table.taxonomy.txt -o data-summary --graphs --percent --format png
Traceback (most recent call last):
  File "/home/srussell/ufits/bin/ufits-summarize_taxonomy.py", line 250, in <module>
    processTax(uniqK, Lk, 'kingdom')
  File "/home/srussell/ufits/bin/ufits-summarize_taxonomy.py", line 163, in processTax
    fig = plt.figure()
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

```
soussell@ubuntu:~/Data/MillerWoods/UFITS$ ufits summarize -i out.otu_table.taxonomy.txt -o data-summary --graphs
Traceback (most recent call last):
  File "/home/srussell/ufits/bin/ufits-summarize_taxonomy.py", line 250, in <module>
    processTax(uniqK, Lk, 'kingdom')
  File "/home/srussell/ufits/bin/ufits-summarize_taxonomy.py", line 163, in processTax
    fig = plt.figure()
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/srussell/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by nextgenusfs** [comment]
Can you post a snippet of what the OTU table looks like, including the taxonomy field?  Never seen this before.  It seems like a matplotlib error, but likely due to the input data not being what it is expecting.  What version of UFITS are you using?  Was OTU table created with same version?

**Comment by MycoMap** [comment]
Usage:       ufits summarize <arguments>
version:     0.7.4

Entire process done with this version.

#OTU ID	I1	I2	I9	I17	I22	I25	I33	I39	II1	II4	II9	II12	II17	II25	II33	II39	III1	III5	III9	III17	III21	III25	III33	III38	IV1	IV6	IV9	IV12	V1	V4	V8	V12	VI1	VI5	VI9	VI12	Taxonomy
M00223:13:000000000-AM23G:1:1101:7202:21158_pident=97.6_OTU466	0	1	0	1	1	1	1	1	0	1	1	0	1	1	0	1	0	0	1	0	0	1	0	0	0	0	1	1	1	1	0	0	1	1	1	1	AB828007;k:Fungi,p:Ascomycota,c:Dothideomycetes,o:Hysteriales,f:Gloniaceae,g:Cenococcum
M00223:13:000000000-AM23G:1:1101:8113:4198_pident=99.1_OTU2125	1	0	0	1	1	1	1	0	1	1	0	1	1	0	1	0	1	1	1	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1

**Comment by nextgenusfs** [comment]
Ok, it’s likely chocking on the labels from your FASTA mock community.  Change those and re-run filtering and then re-run taxonomy.  See the other thread I just responded to with your filtering problem.

**Comment by MycoMap** [comment]
This can be closed.
