### ISSUE TITLE
Appending Taxonomy Error

### ISSUE THREAD

**Issue by MycoMap** [nextgenusfs/amptk#41]
Greetings,

I am getting an error in the final taxonomy step. I have tried it a couple different ways with the same result. Let me know what you would need to diagnose.

^[[92m[Sep 24 09:11 PM]^[[0m: Loading FASTA Records
^[[92m[Sep 24 09:11 PM]^[[0m: 562 OTUs
^[[92m[Sep 24 09:11 PM]^[[0m: Global alignment OTUs with usearch_global (USEARC$
^[[92m[Sep 24 09:11 PM]^[[0m: Classifying OTUs with UTAX (USEARCH)
^[[92m[Sep 24 09:11 PM]^[[0m: Classifying OTUs with SINTAX (USEARCH)
^[[92m[Sep 24 09:11 PM]^[[0m: Appending taxonomy to OTU table and OTUs
Traceback (most recent call last):
  File "/depot/bioinfo/apps/apps/amptk-1.1.2/bin/amptk-assign_taxonomy.py", lin$
    tax = otuDict.get(line[0]) or "No Hit"
NameError: name 'otuDict' is not defined

**Comment by MycoMap** [comment]
Will do

**Comment by bsmoda** [comment]
I also got an error with the taxonomy step, the biom wasn't created:
 [02/22/19 17:05:25]: biom convert -i ../cluster/its2_mosaic_all.final.txt -o ../cluster/its2_mosaic_all.biom.tmp --table-type OTU table --to-json
[02/22/19 17:05:26]: Traceback (most recent call last):
  File "/mnt/data2/lbcb/conda/envs/amptk/bin/biom", line 6, in <module>
    from biom.cli import cli
  File "/mnt/data2/lbcb/conda/envs/amptk/lib/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/mnt/data2/lbcb/conda/envs/amptk/lib/python2.7/site-packages/biom/table.py", line 200, in <module>
    from ._filter import _filter
  File "__init__.pxd", line 861, in init biom._filter (biom/_filter.c:6729)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

[02/22/19 17:05:26]: biom add-metadata -i ../cluster/its2_mosaic_all.biom.tmp -o ../cluster/its2_mosaic_all.biom --observation-metadata-fp ../cluster/
[02/22/19 17:05:27]: Traceback (most recent call last):
  File "/mnt/data2/lbcb/conda/envs/amptk/bin/biom", line 6, in <module>
    from biom.cli import cli
  File "/mnt/data2/lbcb/conda/envs/amptk/lib/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/mnt/data2/lbcb/conda/envs/amptk/lib/python2.7/site-packages/biom/table.py", line 200, in <module>
    from ._filter import _filter
  File "__init__.pxd", line 861, in init biom._filter (biom/_filter.c:6729)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216


The complete log file is attached below.
[its2_mosaic_all.amptk-taxonomy.log](https://github.com/nextgenusfs/amptk/files/2895771/its2_mosaic_all.amptk-taxonomy.log)

**Comment by nextgenusfs** [comment]
Looks like this is not an amptk error -- but rather an error from your install of the `biom` tool.  Try to run this manually and you'll see the error.  You need to fix your `biom` install -- likely a numpy/biom compiliation issue.
```
biom convert -i ../cluster/its2_mosaic_all.final.txt -o ../cluster/its2_mosaic_all.biom.tmp --table-type OTU table --to-json
```
