### ISSUE TITLE
add SILVA/greengenes DB to amptk taxonomy

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/amptk#44]
problem is reformatting the taxonomy information in format needed by UTAX/SINTAX.  I've previously looked at SILVA taxonomy -- the taxonomy appeared to be a hot mess (I'm not a bacteriologist).... So the challenge will be convert the taxonomy strings to proper format

example taxonomy strings:
```
>BOLD:ACI6695;tax=k:Animalia,p:Arthropoda,c:Insecta,o:Coleoptera,f:Elateridae,g:Nipponoelater,s:Nipponoelater babai
>S004604051;tax=k:Fungi,p:Basidiomycota,c:Agaricomycetes,o:Hymenochaetales,f:Hymenochaetaceae,g:Inonotus,s:Sanghuangporus zonatus
>S004127186;tax=k:Fungi,p:Ascomycota
>S004061552;tax=k:Fungi,p:Ascomycota,c:Eurotiomycetes,s:Pyrenula sanguinea
```

**Comment by nextgenusfs** [comment]
update: I've tried this, but the size of the database is large and searches are incredibly slow, need to figure out why before doing this. There seems to be a lot of redundancy in the database, one solution would be to dereplicate and then LCA, but not sure that will then be any better.

**Comment by AlexGaithuma** [comment]
Failed to create database UTAX and SINTAX but usearch created.
my command:

#!/bin/bash
SILVA="/media/bioadmin/Think/MiseqDATA/SILVA_Database"

# download the SILVA_132_SSURef_NR99 database and extract the V4 region
mkdir $SILVA && cd $SILVA
RELEASE=132
URL="https://www.arb-silva.de/fileadmin/silva_databases/release_${RELEASE}/Exports"
INPUT="SILVA_${RELEASE}_SSURef_Nr99_tax_silva.fasta.gz"

# Download and check
wget -c ${URL}/${INPUT}{,.md5} && md5sum -c ${INPUT}.md5

# Define variables and output files
# Primers V3-V4 region (~465 bp) 341F & 805R

OUTPUT="${INPUT/.fasta.gz/_341F_805R.fasta}"
LOG="${INPUT/.fasta.gz/_515F_926R.log}"
PRIMER_F="CCTACGGGNGGCWGCAG"
PRIMER_R="GACTACHVGGGTATCTAATCC"
ANTI_PRIMER_R="GGATTAGATACCCBDGTAGTC"
MIN_LENGTH=32
MIN_F=$(( ${#PRIMER_F} * 2 / 3 ))
MIN_R=$(( ${#PRIMER_R} * 2 / 3 ))

# Trim forward & reverse primers, format
zcat "${INPUT}" | sed '/^>/ ! s/U/T/g' | \
     cutadapt --discard-untrimmed --minimum-length ${MIN_LENGTH} -g "${PRIMER_F}" -O "${MIN_F}" - 2> "${LOG}" | \
     cutadapt --discard-untrimmed --minimum-length ${MIN_LENGTH} -a "${ANTI_PRIMER_R}" -O "${MIN_R}" - 2>> "${LOG}" | \
     sed '/^>/ s/;/|/g ; /^>/ s/ /_/g ; /^>/ s/_/ /1' > "${OUTPUT}"

# Format extracted SILVA database
sed -i 's/:/_/g' $SILVA/${OUTPUT}
sed 's/ Bacteria/;tax=d:Bacteria,/g' $SILVA/${OUTPUT} | \
sed 's/|/p:"/1' | sed 's/|/",c:/1' | sed 's/|/,o:/1' | \
sed 's/|/,f:/1' | sed 's/|/,g:/1' | sed 's/|/,s:/1' > $SILVA/AMPtk_${OUTPUT}

#amptk database
This is my output:

amptk database -i $SILVA/AMPtk_${OUTPUT} -o 16S --format off --create_db usearch \
    --skip_trimming --install --primer_required none --derep_fulllength
-------------------------------------------------------
[12:01:01 PM]: OS: Ubuntu 14.04, 8 cores, ~ 8 GB RAM. Python: 3.4.3
[12:01:01 PM]: AMPtk v1.4.0, USEARCH v9.2.64, VSEARCH v2.9.0
[12:01:01 PM]: Base name set to: /usr/local/lib/python3.4/dist-packages/amptk/DB/16S
[12:01:01 PM]: Working on file: /media/bioadmin/Think/MiseqDATA/SILVA_Database/AMPtk_SILVA_132_SSURef_Nr99_tax_silva_515F_926R.fasta
[12:01:13 PM]: 594,027 records loaded
[12:01:13 PM]: Using 8 cpus to process data
[12:01:49 PM]: 593,752 records passed (99.95%)
[12:01:49 PM]: Errors: 0 no taxonomy info, 0 no ID, 0 length out of range, 275 too many ambiguous bases, 0 no primers found
[12:01:49 PM]: Now dereplicating sequences (collapsing identical sequences)
[12:01:59 PM]: 359,733 records passed (60.56%)
[12:01:59 PM]: Creating USEARCH Database (VSEARCH)
[12:02:18 PM]: Database /usr/local/lib/python3.4/dist-packages/amptk/DB/16S.udb created successfully
-------------------------------------------------------

amptk database -i $SILVA/AMPtk_${OUTPUT} -o 16S_SINTAX --format off --create_db sintax \
    --skip_trimming --install --primer_required none --derep_fulllength
-------------------------------------------------------
[12:03:00 PM]: OS: Ubuntu 14.04, 8 cores, ~ 8 GB RAM. Python: 3.4.3
[12:03:00 PM]: AMPtk v1.4.0, USEARCH v9.2.64, VSEARCH v2.9.0
[12:03:00 PM]: Base name set to: /usr/local/lib/python3.4/dist-packages/amptk/DB/16S_SINTAX
[12:03:00 PM]: Working on file: /media/bioadmin/Think/MiseqDATA/SILVA_Database/AMPtk_SILVA_132_SSURef_Nr99_tax_silva_515F_926R.fasta
[12:03:11 PM]: 594,027 records loaded
[12:03:11 PM]: Using 8 cpus to process data
[12:03:49 PM]: 593,752 records passed (99.95%)
[12:03:49 PM]: Errors: 0 no taxonomy info, 0 no ID, 0 length out of range, 275 too many ambiguous bases, 0 no primers found
[12:03:49 PM]: Now dereplicating sequences (collapsing identical sequences)
[12:03:59 PM]: 359,733 records passed (60.56%)
[12:04:00 PM]: Creating SINTAX Database, this may take awhile
Traceback (most recent call last):
  File "/usr/local/bin/amptk", line 735, in <module>
    main()
  File "/usr/local/bin/amptk", line 726, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.4/dist-packages/amptk/extract_region.py", line 623, in main
    makeDB(OutName, args=args)
  File "/usr/local/lib/python3.4/dist-packages/amptk/extract_region.py", line 418, in makeDB
    amptklib.log.error("There was a problem creating the DB, check the UTAX log file %s" % utax_log)
UnboundLocalError: local variable 'utax_log' referenced before assignment

amptk database -i $SILVA/AMPtk_${OUTPUT} -o 16S_UTAX --format off --create_db sintax \
    --skip_trimming --install --primer_required none --derep_fulllength
-------------------------------------------------------
[12:04:47 PM]: OS: Ubuntu 14.04, 8 cores, ~ 8 GB RAM. Python: 3.4.3
[12:04:47 PM]: AMPtk v1.4.0, USEARCH v9.2.64, VSEARCH v2.9.0
[12:04:47 PM]: Base name set to: /usr/local/lib/python3.4/dist-packages/amptk/DB/16S_UTAX
[12:04:47 PM]: Working on file: /media/bioadmin/Think/MiseqDATA/SILVA_Database/AMPtk_SILVA_132_SSURef_Nr99_tax_silva_515F_926R.fasta
[12:04:59 PM]: 594,027 records loaded
[12:04:59 PM]: Using 8 cpus to process data
[12:05:36 PM]: 593,752 records passed (99.95%)
[12:05:36 PM]: Errors: 0 no taxonomy info, 0 no ID, 0 length out of range, 275 too many ambiguous bases, 0 no primers found
[12:05:36 PM]: Now dereplicating sequences (collapsing identical sequences)
[12:05:46 PM]: 359,733 records passed (60.56%)
[12:05:46 PM]: Creating SINTAX Database, this may take awhile
Traceback (most recent call last):
  File "/usr/local/bin/amptk", line 735, in <module>
    main()
  File "/usr/local/bin/amptk", line 726, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.4/dist-packages/amptk/extract_region.py", line 623, in main
    makeDB(OutName, args=args)
  File "/usr/local/lib/python3.4/dist-packages/amptk/extract_region.py", line 418, in makeDB
    amptklib.log.error("There was a problem creating the DB, check the UTAX log file %s" % utax_log)
UnboundLocalError: local variable 'utax_log' referenced before assignment

**Comment by nextgenusfs** [comment]
Likely running out of memory or the taxonomy labels not formatted correctly. Check the logfile to see what usearch died with.

**Comment by AlexGaithuma** [comment]
usearch9 -makeudb_sintax /usr/local/lib/python3.4/dist-packages/amptk/DB/16S_SINTAX.extracted.fa -output /usr/local/lib/python3.4/dist-packages/amptk/DB/16S_SINTAX.udb -notrunclabels

---Fatal error---
../utaxdata.cpp(1176) assert failed: Size > 0 && Ids != 0

**Comment by nextgenusfs** [comment]
Hopefully that error makes sense - you have sequences (at least one) that doesn’t have any taxonomy information.

**Comment by FilipeMatteoli** [comment]
I am commenting here because it is related, I am trying to build a tailored V4 database out of SILVA NR 132. I guess I've managed to format the headers properly, the fasta has now around 200 Mb. However, after running:

amptk database -i '/media/filipe/84CAA4DCCAA4CC2C/databases/SILVA_fasta/amptk_SILVA_132' -o V4_NR132 --format off --create_db utax --skip_trimming --install --primer_required none --derep_fulllength

I got:
[06:30:23 PM]: OS: debian buster/sid, 16 cores, ~ 66 GB RAM. Python: 3.7.3
[06:30:23 PM]: AMPtk v1.4.0, USEARCH v9.2.64, VSEARCH v2.13.6
[06:30:23 PM]: Base name set to: /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/V4_NR132
[06:30:23 PM]: Working on file: /media/filipe/84CAA4DCCAA4CC2C/databases/SILVA_fasta/amptk_SILVA_132
[06:30:33 PM]: 556,586 records loaded
[06:30:33 PM]: Using 16 cpus to process data
[06:30:46 PM]: 556,389 records passed (99.96%)
[06:30:46 PM]: Errors: 0 no taxonomy info, 0 no ID, 1 length out of range, 196 too many ambiguous bases, 0 no primers found
[06:30:46 PM]: Now dereplicating sequences (collapsing identical sequences)
[06:30:50 PM]: 255,268 records passed (45.86%)
[06:30:50 PM]: Creating UTAX Database, this may take awhile
[07:03:52 PM]: There was a problem creating the DB, check the UTAX log file /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/V4_NR132.utax.log

The utax logfile says:
-------------------
00:00 37Mb      0.1% Reading /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/V4_NR132.extracted.fa^M00:01 112Mb    7
0.6% Reading /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/V4_NR132.extracted.fa^M00:01 142Mb   100.0% Reading /ho
me/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/V4_NR132.extracted.fa
00:01 108Mb     0.1% Converting to upper case                                                                             ^M00:01 108Mb   10
0.0% Converting to upper case
00:01 109Mb     0.1% Word stats              ^M00:02 109Mb    55.9% Word stats^M00:02 109Mb   100.0% Word stats
00:02 109Mb   100.0% Alloc rows
00:02 358Mb     0.1% Build index^M00:03 358Mb    19.3% Build index^M00:04 358Mb    66.9% Build index^M00:04 358Mb   100.0% Build index
00:04 360Mb     0.0% Initialize taxonomy data^M00:05 364Mb    17.6% Initialize taxonomy data^M00:06 373Mb    75.9% Initialize taxonomy data
^M00:06 377Mb   100.0% Initialize taxonomy data
00:06 377Mb     0.0% Building name table     ^M00:06 378Mb   100.0% Building name table
00:06 378Mb  41947 names, tax levels min 2, avg 6.6, max 7

WARNING: 1247 taxonomy nodes have >1 parent
[ then started building a matrix]
27.6% Distance matrix/usort^M33:02 4.3Gb    27.6% Distance matrix/usort
---Fatal error---
Memory limit of 32-bit process exceeded, 64-bit build required
--------------

I guess this is related to the 32bit version of usearch being limited to 4 Gb. My system has 64 Gb.
Is there any way to create this database using vsearch?
Is it possible to split the fasta, loop in the database creation then join files at the end?
Any suggestions would be good.

Best,

**Comment by nextgenusfs** [comment]
UTAX is specific to usearch. The memory limit doesn’t seem to always be consistent, technically it should be 4 GB but that doesn’t mean it can work on files equal to 4 GB. Anyway the current hybrid method will use the entire database with vsearch for global alignment. So you can randomly sub sample the input data to generate the UTAX and sintax databases whole keeping the whole thing for the usearch database.

**Comment by theo-allnutt-bioinformatics** [comment]
Not sure if this will help now but just in case anyone else wants to convert silva to sintax fasta format, I wrote this.. it won't give the proper taxonomic levels to eukaryotes in silva132 but it will work with -makeudb_sintax.
Theo

`#!/usr/bin/env python

#reformats SILVA formatted taxonomy in the header of fasta files to be compatible with usearch and sintax dbs.
#useage:
#reformat_silva.py infile.fasta outfile.fasta

import sys

f= open(sys.argv[1],'r')
h= open(sys.argv[2],'w')
tax=['d','p','c','o','f','g','s']


for i in f:
	out=""
	if i[0]==">":
		k=i.split(";")
		if len(k)>7:
			k=k[-7:]
		acc=k[0].split(" ")[0]
		k[-1]=k[-1].rstrip("\n")
		if " " in k[0]:
			k[0]=k[0].split(" ")[1]
		c=-1
		for x in k:
			c=c+1
			out=out+tax[c]+":"+x+","
		
		out=out.rstrip(",")
		h.write(acc+";tax="+out+"\n")
			
		
	else:
		i=i.replace('U','T')
		h.write(i)`

**Comment by nicolereynolds1** [comment]
I made a script to change the eukaryotic headers. It's probably not the most elegant or efficient solution, but it seems to work.  I used this script first on the SILVA LSU fasta file and then used the script from theo-allnutt-bioinformatics above to get the taxonomy strings correct and replace the Us with Ts. The taxonomy still isn't perfect, but at least it's in the proper format for amptk.

> #!/usr/bin/env python

import sys

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Eukaryota;Opisthokonta;Nucletmycea;",""))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Dikarya;",""))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Eukaryota;Opisthokonta;Holozoa;",""))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Eumetazoa;",""))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Eukaryota;SAR","SAR"))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

with open("SILVA_132_LSUParc_tax_silva.fasta","r") as f:
	newline=[]
	for word in f.readlines():
		newline.append(word.replace("Eukaryota;Archaepalstida","Viridiplantae"))
with open("SILVA_132_LSUParc_tax_silva.fasta","w") as f:
	for line in newline:
		f.writelines(line)

**Comment by nicolereynolds1** [comment]
I think I have the taxonomy fixed, but now when I try to create the database, amptk gives me errors. In the command line it says 
```
[Jan 31 03:57 PM]: Creating SINTAX Database, this may take awhile
Traceback (most recent call last):
  File "/Users/smithlab/miniconda/envs/amptk/bin/amptk", line 736, in <module>
    main()
  File "/Users/smithlab/miniconda/envs/amptk/bin/amptk", line 727, in main
    mod.main(arguments)
  File "/Users/smithlab/miniconda/envs/amptk/lib/python3.7/site-packages/amptk/extract_region.py", line 623, in main
    makeDB(OutName, args=args)
  File "/Users/smithlab/miniconda/envs/amptk/lib/python3.7/site-packages/amptk/extract_region.py", line 418, in makeDB
    amptklib.log.error("There was a problem creating the DB, check the UTAX log file %s" % utax_log)
UnboundLocalError: local variable 'utax_log' referenced before assignment
```
in the log file it says
```
usearch9(16829,0xa98521c0) malloc: *** mach_vm_map(size=2963820544) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug


usearch9 -makeudb_sintax /Users/smithlab/miniconda/envs/amptk/lib/python3.7/site-packages/amptk/DB/LSU_SINTAX.extracted.fa -output /Users/smithlab/miniconda/envs/amptk/lib/python3.7/site-packages/amptk/DB/LSU_SINTAX.udb -notrunclabels

---Fatal error---
Memory limit of 32-bit process exceeded, 64-bit build required
```
### I tried Googling malloc_error_break and the results I found suggested that the script needs to be debugged to see where the error is occurring and then insert the breakpoint. I do not know how to do this, so do you have any suggestions?

**Comment by nextgenusfs** [comment]
Malloc errors are memory related, so the free version of usearch is 32 but and thus the file you are trying to make a database out of is too large and it errors. So need to reduce the size to build the sintax and utax databases. The global alignment or usearch uses vsearch which doesn’t have the memory limit. Look at the readthedocs manual  on how I subsampled the data for other databases to build sintax and utax.

**Comment by nicolereynolds2** [comment]
Going back to the Green Genes question, I have made an AMPtk formatted Green Genes database (too big to upload here, so I've put it [here](https://osf.io/cz3mh/) (gg_13_5_replace), which is also where the 28S database I made (RDP_SILVA_LSU_update) is stored). I added a few endosymbiont sequences (for the specific project I'm working on) and some fungal 18S sequences because the primers we've been using sometimes amplify fungal sequences.

I was able to successfully install it into AMPtk.
