### ISSUE TITLE
amptk v1.2.5 taxonomy error

### ISSUE THREAD

**Issue by AlexGaithuma** [nextgenusfs/amptk#45]
I built a custom 16s database:
bioadmin@bioadmin-B75M-D3V-JP[DB] amptk database -i Extra_rdp_v16.fa -o 16S --format off --create_db utax --skip_trimming --keep_all                 [11:39午前]
-------------------------------------------------------
[11:39:44 AM]: OS: linux2, 8 cores, ~ 8 GB RAM. Python: 2.7.15
[11:39:44 AM]: AMPtk v1.2.5, USEARCH v9.2.64, VSEARCH v2.9.0
[11:39:44 AM]: Working on file: Extra_rdp_v16.fa
[11:39:45 AM]: 13,225 records loaded
[11:39:45 AM]: Using 8 cpus to process data
[11:39:46 AM]: 13,164 records passed (99.54%)
[11:39:46 AM]: Errors: 0 no taxonomy info, 0 length out of range, 61 too many ambiguous bases, 0 no primers found
[11:39:46 AM]: Creating UTAX Database, this may take awhile
[11:49:33 AM]: Database /home/bioadmin/packages/amptk-1.2.5/DB/16S.udb created successfully

But assigning taxonomy doesn't work:
bioadmin@bioadmin-B75M-D3V-JP[Kafue_MG_amptk] amptk taxonomy -f ./$NAME.lulu.otus.fa -i ./$NAME.lulu.otu_table.txt -m ./$NAME.mapping_file.txt -d 16S -o $NAME
-------------------------------------------------------
[12:07:37 PM]: OS: linux2, 8 cores, ~ 8 GB RAM. Python: 2.7.15
[12:07:37 PM]: AMPtk v1.2.5, USEARCH v9.2.64, VSEARCH v2.9.0
[12:07:37 PM]: Loading FASTA Records
[12:07:37 PM]: 265 OTUs
[12:07:37 PM]: Global alignment OTUs with usearch_global (USEARCH)
[12:07:44 PM]: Classifying OTUs with UTAX (USEARCH)
[12:07:44 PM]: Classifying OTUs with SINTAX (USEARCH)
Traceback (most recent call last):
  File "/home/bioadmin/packages/amptk-1.2.5/bin/amptk-assign_taxonomy.py", line 286, in <module>
    utaxDict = amptklib.classifier2dict(utax_out, args.utax_cutoff)
  File "/home/bioadmin/packages/amptk-1.2.5/lib/amptklib.py", line 1357, in classifier2dict
    ClassyDict[ID] = (score, passtax)
UnboundLocalError: local variable 'score' referenced before assignment

**Comment by nextgenusfs** [comment]
Is there any more information in the logfile?  Can you verify that the file in your DB folder location called 16S.extracted.fa is not empty and it contains the sequences you expect?  And then lastly the script for sintax should have been writing to file, is that file empty or what does it contain?

**Comment by AlexGaithuma** [comment]
> Is there any more information in the logfile? Can you verify that the file in your DB folder location called 16S.extracted.fa is not empty and it contains the sequences you expect? And then lastly the script for sintax should have been writing to file, is that file empty or what does it contain?

Thanks for your prompt reply,
1. 16S.extracted.fa is not empty and it contains expected sequences,
2.  Contents of the sintax script look as follows:
ASV41	d:Bacteria(1.0000)	+	d:Bacteria
ASV42	d:Bacteria(1.0000),p:"Proteobacteria"(0.4800),c:Gammaproteobacteria(0.4300),o:"Enterobacteriales"(0.3000),f:Enterobacteriaceae(0.3000),g:Biostraticola(0.1500)	+	d:Bacteria
ASV57	d:Bacteria(0.9900),p:Firmicutes(0.2500),c:Clostridia(0.1200),o:Clostridiales(0.1200),f:"Nitrospiraceae"(0.0800),g:Nitrospira(0.0800)	-	d:Bacteria
ASV45	d:Bacteria(1.0000),p:"Proteobacteria"(0.1700),c:Gammaproteobacteria(0.1300),o:"Enterobacteriales"(0.1100),f:Enterobacteriaceae(0.1100),g:Biostraticola(0.0800)	+	d:Bacteria
ASV55	d:Bacteria(1.0000),p:"Proteobacteria"(0.1200),c:Gammaproteobacteria(0.1200),o:"Enterobacteriales"(0.0300),f:Enterobacteriaceae(0.0300),g:Aeromonas(0.0200)	+	d:Bacteria

3. log file looks like this:
[01/07/19 18:11:11]: /home/bioadmin/packages/amptk-1.2.5/bin/amptk-assign_taxonomy.py --method hybrid -f ./Kafue_MG.lulu.otus.fa -i ./Kafue_MG.lulu.otu_table.txt -m ./Kafue_MG.mapping_file.txt -d 16S -o Kafue_MG

[01/07/19 18:11:11]: OS: linux2, 8 cores, ~ 8 GB RAM. Python: 2.7.15
[01/07/19 18:11:11]: Python Modules: numpy v1.15.2, pandas v0.23.4, matplotlib v2.2.3, psutil v5.4.7, natsort v5.4.0, biopython v1.68, edlib v1.2.3, biom-format v2.1.7
[01/07/19 18:11:11]: AMPtk v1.2.5, USEARCH v9.2.64, VSEARCH v2.9.0
[01/07/19 18:11:11]: Loading FASTA Records
[01/07/19 18:11:11]: 265 OTUs
[01/07/19 18:11:11]: Global alignment OTUs with usearch_global (USEARCH)
[01/07/19 18:11:11]: usearch9 -usearch_global ./Kafue_MG.lulu.otus.fa -db /home/bioadmin/packages/amptk-1.2.5/DB/16S.udb -userout Kafue_MG.usearch.txt -id 0.7 -strand both -output_no_hits -maxaccepts 0 -top_hits_only -userfields query+target+id -threads 8
[01/07/19 18:11:18]: usearch v9.2.64_i86linux32, 4.0Gb RAM (8.0Gb total), 8 cores
(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: akiariegaithuma@gmail.com


[01/07/19 18:11:18]: 00:00 3.9Mb     0.0% Rows
00:00 78Mb    100.0% Rows
00:00 78Mb   Read taxonomy info...done.
00:00 79Mb   Reading pointers...done.
00:00 81Mb   Reading db seqs...done.
00:00 133Mb     0.1% Searching Kafue_MG.lulu.otus.fa, 0.0% matched
00:01 223Mb     4.5% Searching Kafue_MG.lulu.otus.fa, 100.0% matched
00:02 261Mb    15.6% Searching Kafue_MG.lulu.otus.fa, 91.2% matched 
00:03 270Mb    25.3% Searching Kafue_MG.lulu.otus.fa, 93.2% matched
00:04 286Mb    49.5% Searching Kafue_MG.lulu.otus.fa, 91.9% matched
00:05 286Mb    62.5% Searching Kafue_MG.lulu.otus.fa, 91.7% matched
00:06 287Mb    79.5% Searching Kafue_MG.lulu.otus.fa, 90.6% matched
00:07 301Mb   100.0% Searching Kafue_MG.lulu.otus.fa, 89.1% matched

[01/07/19 18:11:18]: Classifying OTUs with UTAX (USEARCH)
[01/07/19 18:11:18]: usearch9 -utax ./Kafue_MG.lulu.otus.fa -db /home/bioadmin/packages/amptk-1.2.5/DB/16S.udb -utaxout Kafue_MG.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 8
[01/07/19 18:11:18]: usearch v9.2.64_i86linux32, 4.0Gb RAM (8.0Gb total), 8 cores
(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: akiariegaithuma@gmail.com


[01/07/19 18:11:18]: 00:00 3.8Mb     0.0% Rows
00:00 78Mb    100.0% Rows
00:00 78Mb   Read taxonomy info...done.
00:00 79Mb   Reading pointers...done.
00:00 81Mb   Reading db seqs...done.
00:00 133Mb     0.1% 0 seqs, 0.0% at phylum, 0.0% genus (P > 0.00)
00:00 210Mb   100.0% 265 seqs, 63.8% at phylum, 16.2% genus (P > 0.80)

WARNING: Option -notrunclabels not used


[01/07/19 18:11:18]: Classifying OTUs with SINTAX (USEARCH)
[01/07/19 18:11:18]: usearch9 -sintax ./Kafue_MG.lulu.otus.fa -db /home/bioadmin/packages/amptk-1.2.5/DB/16S.extracted.fa -tabbedout Kafue_MG.sintax.txt -sintax_cutoff 0.8 -strand both -threads 8
[01/07/19 18:11:20]: usearch v9.2.64_i86linux32, 4.0Gb RAM (8.0Gb total), 8 cores
(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: akiariegaithuma@gmail.com


[01/07/19 18:11:20]: 00:00 37Mb      0.1% Reading /home/bioadmin/packages/amptk-1.2.5/DB/16S.extracted.fa
00:00 61Mb    100.0% Reading /home/bioadmin/packages/amptk-1.2.5/DB/16S.extracted.fa
00:00 27Mb      0.1% Masking (fastnucleo)                                           
00:00 27Mb    100.0% Masking (fastnucleo)
00:00 28Mb      0.1% Word stats          
00:01 28Mb     40.2% Word stats
00:01 28Mb    100.0% Word stats
00:01 28Mb    100.0% Alloc rows
00:01 99Mb      0.1% Build index
00:02 99Mb     90.8% Build index
00:02 99Mb    100.0% Build index
00:02 99Mb      0.0% Initialize taxonomy data
00:02 99Mb    100.0% Initialize taxonomy data
00:02 99Mb      0.0% Building name table     
00:02 99Mb    100.0% Building name table
00:02 99Mb   2778 names, tax levels min 1, avg 5.9, max 6
00:02 133Mb     0.1% Processing
00:02 202Mb   100.0% Processing

**Comment by AlexGaithuma** [comment]
Thank you for your Feedback.

I found out that the problem occured during database creation.
There was a problem with the format of the database input file "-i Extra_rdp_v16.fa" file.
There were some instances with a comma and others with a colon:  

>86332;tax=d:Bacteria,p:"Proteobacteria",c:Alphaproteobacteria,o:"Rickettsiales",f:Anaplasmataceae,g:Wolbachia;

and

>86332;tax=d:Bacteria,p:"Proteobacteria",c:Alphaproteobacteria,o:"Rickettsiales",f:Anaplasmataceae,g:Wolbachia;

Once I resolved this, there was no error.

**Comment by nextgenusfs** [comment]
Great, glad you got it sorted!
