### ISSUE TITLE
amptk taxonomy does not create biom

### ISSUE THREAD

**Issue by FilipeMatteoli** [nextgenusfs/amptk#61]
Hello,
I am having issues with taxonomy command, biom files are not being produced. Every command is running smoothly, installation is fresh. Command was as follows:
```
amptk taxonomy -f '/media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa' \
   -i '/media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.final.txt' \
   -o tax -d ITS1 \
   -m '/media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/amptkillumina.mapping_file.txt' \
   --tax_filter Fungi
```
I've checked that biom version under conda is working (v 2.1.7.)

I tried to manually create the biom file but whenever I add metadata the taxonomy disappears from the OTUs. Checking an older logfile of amptk which completed successfully I noticed that the software uses an option "--observation-metadata-fp /media/filipe/amptk_old/amtpk_taxonomy_2.qiime.taxonomy.txt" (in biom add-metadata command)

However, I could not find this file .qiime.taxonomy.txt to manually create a biom table with both  observation and sample metadata.

Log file: 
```
[08/01/19 16:04:03]: /home/filipe/miniconda3/envs/amptk/bin/amptk taxonomy -f /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa -i /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.final.txt -o tax -d ITS1 -m /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/amptkillumina.mapping_file.txt --tax_filter Fungi

[08/01/19 16:04:03]: OS: debian buster/sid, 16 cores, ~ 66 GB RAM. Python: 3.7.3
[08/01/19 16:04:03]: Python Modules: numpy v1.16.4, pandas v0.25.0, matplotlib v3.1.1, psutil v5.6.3, natsort v6.0.0, biopython v1.74, edlib v1.2.4.post1, biom-format v2.1.7
[08/01/19 16:04:03]: AMPtk v1.4.0, USEARCH v9.2.64, VSEARCH v2.13.6
[08/01/19 16:04:03]: Loading FASTA Records
[08/01/19 16:04:03]: 581 OTUs
[08/01/19 16:04:03]: Global alignment OTUs with usearch_global (VSEARCH) against ITS.udb
[08/01/19 16:04:03]: vsearch --usearch_global /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa --db /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/ITS.udb --userout tax.usearch.txt --id 0.7 --strand both --output_no_hits --maxaccepts 0 --top_hits_only --userfields query+target+id --notrunclabels --threads 16
[08/01/19 16:04:18]: b'vsearch v2.13.6_linux_x86_64, 62.9GB RAM, 16 cores\nhttps://github.com/torognes/vsearch\n\nReading UDB file /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/ITS.udb 100%\nReorganizing data in memory 100%\nCreating bitmaps 100%\nParsing abundances 100%\n598931036 nt in 1130202 seqs, min 100, max 6778, avg 530\nSearching 100%\nMatching unique query sequences: 507 of 581 (87.26%)\n'
[08/01/19 16:04:18]: Classifying OTUs with UTAX (USEARCH)
[08/01/19 16:04:18]: usearch9 -utax /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa -db /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/ITS1_UTAX.udb -utaxout tax.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 16
[08/01/19 16:04:18]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (66.0Gb total), 16 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: matteolifilipe@gmail.com\n\n'
[08/01/19 16:04:18]: b'00:00 3.8Mb     0.0% Rows\r00:00 69Mb    100.0% Rows\r\n00:00 69Mb   Read taxonomy info...done.\n00:00 72Mb   Reading pointers...done.\n00:00 80Mb   Reading db seqs...done.\n00:00 130Mb     0.1% 0 seqs, 0.0% at phylum, 0.0% genus (P > 0.00)\r00:00 310Mb   100.0% 581 seqs, 75.9% at phylum, 13.3% genus (P > 0.80)\r\n\nWARNING: Option -notrunclabels not used\n\n'
[08/01/19 16:04:18]: Classifying OTUs with SINTAX (USEARCH)
[08/01/19 16:04:18]: usearch9 -sintax /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa -db /home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/DB/ITS_SINTAX.udb -tabbedout tax.sintax.txt -sintax_cutoff 0.8 -strand both -threads 16
[08/01/19 16:04:24]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (66.0Gb total), 16 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: matteolifilipe@gmail.com\n\n'
[08/01/19 16:04:24]: b'00:00 3.8Mb     0.0% Rows\r00:00 311Mb   100.0% Rows\r\n00:00 311Mb  Read taxonomy info...done.\n00:00 318Mb  Reading pointers...done.\n00:00 333Mb  Reading db seqs...done.\n00:00 445Mb     0.1% Processing\r00:01 609Mb     8.6% Processing\r00:02 609Mb    27.6% Processing\r00:03 609Mb    43.3% Processing\r00:04 609Mb    62.5% Processing\r00:05 609Mb    78.9% Processing\r00:06 609Mb    97.3% Processing\r00:06 609Mb   100.0% Processing\r\n'
[08/01/19 16:04:24]: UTAX results parsed, resulting in 560 taxonomy predictions
[08/01/19 16:04:24]: SINTAX results parsed, resulting in 472 taxonomy predictions
[08/01/19 16:04:25]: Global alignment results parsed, resulting in 581 taxonomy predictions
[08/01/19 16:04:25]: Combined OTU taxonomy dictionary contains 581 taxonomy predictions
[08/01/19 16:04:25]: Appending taxonomy to OTU table and OTUs
[08/01/19 16:04:25]: Found 94 OTUs not matching Fungi, writing 487 Fungi hits to taxonomy OTU table
[08/01/19 16:04:25]: Generating phylogenetic tree
[08/01/19 16:04:25]: usearch9 -cluster_agg /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa -treeout tax.tree.phy
[08/01/19 16:04:26]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (66.0Gb total), 16 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: matteolifilipe@gmail.com\n\n'
[08/01/19 16:04:26]: b'00:00 37Mb      0.1% Reading /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa\r00:00 40Mb    100.0% Reading /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.filtered.otus.fa\r\n00:00 7.6Mb     0.1% Word stats                                                                                                       \r00:00 7.6Mb   100.0% Word stats\r\n00:00 7.6Mb   100.0% Alloc rows\r\n00:00 8.2Mb     0.1% Build index\r00:00 8.2Mb   100.0% Build index\r\n00:00 84Mb      0.2% Distance matrix/usort\r00:01 105Mb    85.9% Distance matrix/usort\r00:01 105Mb   100.0% Distance matrix/usort\r\n00:01 108Mb     0.2% Building tree        \r00:01 108Mb   100.0% Building tree\r\n'
[08/01/19 16:04:26]: Taxonomy finished: tax.taxonomy.txt
[08/01/19 16:04:26]: Classic OTU table with taxonomy: tax.otu_table.taxonomy.txt
[08/01/19 16:04:27]: biom convert -i tax.otu_table.tmp -o tax.biom.tmp --table-type OTU table --to-json
[08/01/19 16:04:27]: b'Traceback (most recent call last):\n  File "/home/filipe/miniconda3/envs/amptk/bin/biom", line 11, in <module>\n    sys.exit(cli())\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 717, in main\n    rv = self.invoke(ctx)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 555, in invoke\n    return callback(*args, **kwargs)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/table_converter.py", line 129, in convert\n    table_type, process_obs_metadata, tsv_metadata_formatter)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/table_converter.py", line 207, in _convert\n    write_biom_table(result, fmt, output_filepath)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/util.py", line 26, in write_biom_table\n    f.write(table.to_json(biom.parse.generatedby()))\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/table.py", line 4497, in to_json\n    raise TableException("Unsupported matrix data type.")\nbiom.exception.TableException: Unsupported matrix data type.\n'
[08/01/19 16:04:27]: biom add-metadata -i tax.biom.tmp -o tax.biom --observation-metadata-fp tax.qiime.taxonomy.txt -m /media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/amptkillumina.mapping_file.txt --sc-separated taxonomy --output-as-json
[08/01/19 16:04:28]: b'Traceback (most recent call last):\n  File "/home/filipe/miniconda3/envs/amptk/bin/biom", line 11, in <module>\n    sys.exit(cli())\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 717, in main\n    rv = self.invoke(ctx)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 555, in invoke\n    return callback(*args, **kwargs)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/metadata_adder.py", line 83, in add_metadata\n    table = load_table(input_fp)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/parse.py", line 658, in load_table\n    with biom_open(f) as fp:\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/contextlib.py", line 112, in __enter__\n    return next(self.gen)\n  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/util.py", line 444, in biom_open\n    raise ValueError("The file \'%s\' is empty and can\'t be parsed" % fp)\nValueError: The file \'tax.biom.tmp\' is empty and can\'t be parsed\n'
[08/01/19 16:04:28]: BIOM OTU table created: tax.biom
[08/01/19 16:04:28]: OTUs with taxonomy: tax.otus.taxonomy.fa
[08/01/19 16:04:28]: OTU phylogeny: tax.tree.phy
```
Any ideas about how can I fix "raise TableException("Unsupported matrix data type.") ?

**Comment by nextgenusfs** [comment]
Try running with `--debug` option which should save all intermediate files, let me know if the `*.qiime.taxonomy.txt` file is not being created.  I suspect its a `biom` problem.

**Comment by FilipeMatteoli** [comment]
Just did, now I got more output files including the tax.qiime.taxonomy.txt.

**Comment by nextgenusfs** [comment]
Okay run the biom command manually and what happens?

**Comment by FilipeMatteoli** [comment]
Running within amptk conda env:

biom convert -i '/media/filipe/84CAA4DCCAA4CC2C/datasets/lorena-analysis/z_august_final/filter_out/filter.final.txt' --table-type 'OTU table' --to-json -o tax.otu_table_biom_temp
Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/amptk/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/home/filipe/miniconda3/envs/amptk/lib/python3.7/site-packages/biom/table.py", line 4497, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.

-> If i run from base biom (installed through apt) it finishes smoothly. Probably issue is in conda's biom

**Comment by nextgenusfs** [comment]
Yes I’ve seen this before with other versions. You can remove it from environment and install with pip as well, amptk just needs to have it in its environment path.

**Comment by nextgenusfs** [comment]
I think this describes the problem https://github.com/biocore/biom-format/issues/816.  Seems like scipy v1.3.0 is the problem, so either upgrade or downgrade.  On next release I will make sure to pin the proper version.
