### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by Alenap26** [nextgenusfs/amptk#67]
Hello, 
I'm trying to run:
`amptk taxonomy -f miseq.cluster.otus.fa -i miseq.otu_table.txt -m miseq.mapping_file.txt -d 16S -o miseq`

The error seems about 16S db, is it possible ? I'm using AMPtk v1.4.2, and default db 16S.

-------------------------------------------------------
```
[05:22:01 PM]: OS: CentOS Linux 7.4.1708, 36 cores, ~ 131 GB RAM. Python: 3.6.7
[05:22:02 PM]: AMPtk v1.4.2, USEARCH v9.2.64, VSEARCH v2.10.4
[05:22:02 PM]: Loading FASTA Records
[05:22:02 PM]: 6,512 OTUs
[05:22:02 PM]: Global alignment OTUs with usearch_global (VSEARCH) against 16S.udb
[05:22:28 PM]: Classifying OTUs with UTAX (USEARCH)
[05:22:28 PM]: Classifying OTUs with SINTAX (USEARCH)
[05:22:31 PM]: UTAX results empty
```
```
Traceback (most recent call last):
  File "/path/anaconda3/envs/amptk_env/bin/amptk", line 737, in <module>
    main()
  File "/path/anaconda3/envs/amptk_env/bin/amptk", line 728, in main
    mod.main(arguments)
  File "/path/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/assign_taxonomy.py", line 316, in main
    usearchDict = amptklib.usearchglobal2dict(usearch_out)
  File "/path/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/amptklib.py", line 1436, in usearchglobal2dict
    pident = float(cols[-1]) / 100
ValueError: could not convert string to float: 'CP000875_S000965246;tax=k:Bacteria,p:"Chloroflexi",c:Chlor'
```

**Comment by nextgenusfs** [comment]
Did it create a utax logfile?  Need to determine why UTAX search failed -- as here says that results were empty.

**Comment by Alenap26** [comment]
Ok, I'm pasting the log error of UTAX:
`[02/26/20 18:58:41]: Classifying OTUs with UTAX (USEARCH)
[02/26/20 18:58:41]: usearch9 -utax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb -utaxout miseq.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 36
[02/26/20 18:58:41]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (131Gb total), 36 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: alessandro.napoli@uniroma2.it\n\n'
[02/26/20 18:58:41]: b'00:00 3.8Mb     0.0% Rows\r00:00 78Mb    100.0% Rows\r\n00:00 78Mb   Reading pointers...done.\n00:00 80Mb   Reading db seqs...done.\n00:00 132Mb     0.1% 0 seqs, 0.0% at phylum, 0.0% genus (P > 0.00)\r\n\nusearch9 -utax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb -utaxout miseq.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 36\n\n---Fatal error---\n../makesearcher.cpp(354) assert failed: udb->m_UTaxData != 0\n'
[02/26/20 18:58:41]: Classifying OTUs with SINTAX (USEARCH)
[02/26/20 18:58:41]: usearch9 -sintax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S_SINTAX.udb -tabbedout miseq.sintax.txt -sintax_cutoff 0.8 -strand both -threads 36
[02/26/20 18:58:42]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (131Gb total), 36 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: alessandro.napoli@uniroma2.it\n\n'
[02/26/20 18:58:42]: b'00:00 3.8Mb     0.0% Rows\r00:00 14Mb    100.0% Rows\r\n00:00 14Mb   Read taxonomy info...done.\n00:00 14Mb   Reading pointers...done.\n00:00 15Mb   Reading db seqs...done.\n00:00 51Mb      0.1% Processing\r00:01 173Mb    39.6% Processing\r00:01 173Mb   100.0% Processing\r\n'
[02/26/20 18:58:42]: UTAX results empty`

**Comment by Alenap26** [comment]
I also tried with usearch10:

```
`[02/27/20 10:05:45]: Classifying OTUs with UTAX (USEARCH)
[02/27/20 10:05:45]: usearch10 -utax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb -utaxout miseq.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 36
[02/27/20 10:05:45]: b'\n\nInvalid command line\nUnknown option utax\n\n'
[02/27/20 10:05:45]: Classifying OTUs with SINTAX (USEARCH)
[02/27/20 10:05:45]: usearch10 -sintax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S_SINTAX.udb -tabbedout miseq.sintax.txt -sintax_cutoff 0.8 -strand both -threads 36
[02/27/20 10:05:45]: b'usearch v10.0.240_i86linux32, 4.0Gb RAM (131Gb total), 36 cores\n(C) Copyright 2013-17 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: alessandro.napoli@uniroma2.it\n\n'
[02/27/20 10:05:45]: b'00:00 3.6Mb     0.0% Rows\r00:00 14Mb    100.0% Rows\r\n00:00 14Mb   Read taxonomy info...done.\n\n\nusearch10 -sintax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S_SINTAX.udb -tabbedout miseq.sintax.txt -sintax_cutoff 0.8 -strand both -threads 36\n\n---Fatal error---\n.udb magic4 0x55545838 should be 0x55444234\n'
[02/27/20 10:05:45]: UTAX results empty`
```

**Comment by Alenap26** [comment]
I looked in another RUN that I was done on another server, and I found (in that run who had made no mistakes)  
`No hit` in the UTAX column in file missed.taxonomy.txt, so I think that the problem is not
`UTAX results empty`
because in that Run I hadn't had any mistakes like:
`ValueError: could not convert string to float`

Thats the all content of taxonomy.log file:

```
`[02/27/20 18:40:08]: /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/bin/amptk taxonomy -f miseq.cluster.otus.fa -i miseq.otu_table.txt -d 16S -o miseq

[02/27/20 18:40:08]: OS: CentOS Linux 7.4.1708, 36 cores, ~ 131 GB RAM. Python: 3.6.7
[02/27/20 18:40:08]: Python Modules: numpy v1.18.1, pandas v1.0.1, matplotlib v3.1.3, psutil v5.7.0, natsort v7.0.1, biopython v1.76, edlib v1.2.3.post1, biom-format v2.1.6
[02/27/20 18:40:08]: AMPtk v1.4.2, USEARCH v9.2.64, VSEARCH v2.14.2
[02/27/20 18:40:08]: Loading FASTA Records
[02/27/20 18:40:09]: 6,512 OTUs
[02/27/20 18:40:09]: Global alignment OTUs with usearch_global (VSEARCH) against 16S.udb

[02/27/20 18:40:09]: vsearch --usearch_global miseq.cluster.otus.fa --db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb --userout miseq.usearch.txt --id 0.7 --strand both --output_no_hits --maxaccepts 0 --top_hits_only --userfields query+target+id --notrunclabels --threads 36
[02/27/20 18:40:36]: b'vsearch v2.14.2_linux_x86_64, 125.1GB RAM, 36 cores\nhttps://github.com/torognes/vsearch\n\nReading UDB file /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb 100%\nReorganizing data in memory 100%\nCreating bitmaps 100%\nParsing abundances 100%\n18961589 nt in 13118 seqs, min 320, max 2205, avg 1445\nSearching'

[02/27/20 18:40:36]: Classifying OTUs with UTAX (USEARCH)
[02/27/20 18:40:36]: usearch9 -utax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb -utaxout miseq.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 36
[02/27/20 18:40:37]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (131Gb total), 36 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: alessandro.napoli@uniroma2.it\n\n'
[02/27/20 18:40:37]: b'00:00 3.8Mb     0.0% Rows\r00:01 15Mb     14.7% Rows\r00:01 78Mb    100.0% Rows\r\n00:01 78Mb   Reading pointers...done.\n00:01 80Mb   Reading db seqs...done.\n00:01 132Mb     0.1% 0 seqs, 0.0% at phylum, 0.0% genus (P > 0.00)\r\n\nusearch9 -utax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S.udb -utaxout miseq.utax.txt -utax_cutoff 0.8 -strand plus -notrunclabels -threads 36\n\n---Fatal error---\n../makesearcher.cpp(354) assert failed: udb->m_UTaxData != 0\n'
[02/27/20 18:40:37]: Classifying OTUs with SINTAX (USEARCH)
[02/27/20 18:40:37]: usearch9 -sintax miseq.cluster.otus.fa -db /galileo/home/userexternal/anapoli0/anaconda3/envs/amptk_env/lib/python3.6/site-packages/amptk/DB/16S_SINTAX.udb -tabbedout miseq.sintax.txt -sintax_cutoff 0.8 -strand both -threads 36
[02/27/20 18:40:40]: b'usearch v9.2.64_i86linux32, 4.0Gb RAM (131Gb total), 36 cores\n(C) Copyright 2013-16 Robert C. Edgar, all rights reserved.\nhttp://drive5.com/usearch\n\nLicense: alessandro.napoli@uniroma2.it\n\n'
[02/27/20 18:40:40]: b'00:00 3.8Mb     0.0% Rows\r00:00 14Mb    100.0% Rows\r\n00:00 14Mb   Read taxonomy info...done.\n00:00 14Mb   Reading pointers...done.\n00:00 15Mb   Reading db seqs...done.\n00:00 51Mb      0.1% Processing\r00:01 980Mb     3.2% Processing\r00:02 980Mb    35.2% Processing\r00:03 980Mb    72.2% Processing\r00:03 980Mb   100.0% Processing\r\n'
[02/27/20 18:40:40]: UTAX results empty
[02/27/20 18:40:41]: SINTAX results parsed, resulting in 6,131 taxonomy predictions`
```
