### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by kjmarsh** [nextgenusfs/amptk#73]
Hello,
I'm trying to run the preprocessing script on my R1 and R2 illumina files in my 'CO1_seq_files' folder using:
`amptk illumina -i CO1_seq_files -o CO1_amptk_out -f COI-F -r COI-R`

with AMPtk v1.4.2 and get the following error:

> [10:13:11 AM]: OS: debian stretch/sid, 4 cores, ~ 8 GB RAM. Python: 3.7.6
Traceback (most recent call last):
  File "/home/kirstymarsh/miniconda3/envs/amptk/bin/amptk", line 737, in <module>
    main()
  File "/home/kirstymarsh/miniconda3/envs/amptk/bin/amptk", line 728, in main
    mod.main(arguments)
  File "/home/kirstymarsh/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/process_illumina_folder.py", line 204, in main
    amptklib.versionDependencyChecks(usearch)
  File "/home/kirstymarsh/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/amptklib.py", line 196, in versionDependencyChecks
    if not gvc(usearch_version, usearch_pass):
  File "/home/kirstymarsh/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/amptklib.py", line 184, in gvc
    if versiontuple(input) >= versiontuple(check):
  File "/home/kirstymarsh/miniconda3/envs/amptk/lib/python3.7/site-packages/amptk/amptklib.py", line 181, in versiontuple
    return tuple(map(int, (v.split("."))))
ValueError: invalid literal for int() with base 10: ''

I'm not sure where the issue comes from? The 'CO1_amptk_out' folder and ' CO1_amptk_out.amptk-demux' file seem to have been created, but are empty. Could you give me any idea what is happening here?

Thank you

**Comment by nextgenusfs** [comment]
It is an error in parsing the usearch version number, might be related to python version. You could try to downgrade python to 3.6 and see if you get same error or not. Otherwise confirm that you have usearch9 installed and it is in your PATH.
