### ISSUE TITLE
Custom 16S database not found after successful installation

### ISSUE THREAD

**Issue by JonathanVanHamme** [nextgenusfs/amptk#80]
Hi Jon,

I have been trying to install an HSP60 database in AMPtk 1.5.1 by following the instructions you have for the 16S database. All goes well with the installation, the database is visible when I query "amptk info", but when I run a taxonomy assignment it tells me that I "have not selected a database".

To ensure I wasn't messing something else up, I downloaded the rdp database and installed under the name "test". Ended up with the same error.

`$ amptk taxonomy -f file.filtered.otus.fa -i file.final.txt -m mapping.txt -d test -o test
-------------------------------------------------------
[02:37:43 PM]: OS: debian buster/sid, 24 cores, ~ 396 GB RAM. Python: 3.7.8
[02:37:43 PM]: AMPtk v1.5.1, VSEARCH v2.15.1
[02:37:43 PM]: You have not selected a database, need either --db, --utax_db, --usearch_db, or --fasta_db`

The log file is sparse:

`[03/15/21 14:37:43]: OS: debian buster/sid, 24 cores, ~ 396 GB RAM. Python: 3.7.8
[03/15/21 14:37:43]: Python Modules: numpy v1.19.4, pandas v1.1.4, matplotlib v3.3.2, psutil v5.7.3, natsort v7.0.1, biopython v1.78, edlib v1.3.8.post1, biom-format v2.1.9`

Hope all is well,
Jon

**Comment by nextgenusfs** [comment]
Sorry for the delayed response -- can you show me the output of `amptk info`?

**Comment by JonathanVanHamme** [comment]
No worries, Jon, glad you are still about.

Apologies for all of the information below, there is a lot going on in my database area - the "test" database is the one that contains just a few records from rdp.

```
$ amptk info
------------------------------
Running AMPtk v 1.5.1
------------------------------
Taxonomy Databases Installed: /results/Miniconda/miniconda3/envs/amptk151/lib/python3.7/site-packages/amptk/DB
------------------------------
  DB_name    DB_type                         FASTA                         Fwd Primer Rev Primer Records  Source  Version      Date   
         16S  vsearch                               rdp_16s_v16.kingdom.fa      None        None    13118    RDP       v16  2019-02-18
  16S_SINTAX   sintax                               rdp_16s_v16.kingdom.fa     515FB       806RB     9679    RDP       v16  2019-02-18
         COI  vsearch                     arth-chord.bold-reformated.fasta   LCO1490   mlCOIintR  1894144   BOLD  20201109  2020-11-12
         HSP  vsearch                              edit_cnp60_OSF_AMPtk.fa      None        None     5320                   2021-03-13
       HSP60  vsearch                              edit_cnp60_OSF_AMPtk.fa      None        None     5320                   2021-03-13
         ITS  vsearch                    UNITE_public_all_04.02.2020.fasta    ITS1-F        ITS4  1087662  UNITE       8.2  2020-07-18
 ITS1_SINTAX   sintax    sh_general_release_dynamic_s_all_04.02.2020.fasta    ITS1-F        ITS2   125067  UNITE       8.2  2020-07-18
   ITS1_UTAX     utax  sh_general_release_dynamic_all_02.02.2019_dev.fasta    ITS1-F        ITS2    59710  UNITE       8.0  2019-02-12
 ITS2_SINTAX   sintax    sh_general_release_dynamic_s_all_04.02.2020.fasta     fITS7        ITS4   103543  UNITE       8.2  2020-07-18
   ITS2_UTAX     utax  sh_general_release_dynamic_all_02.02.2019_dev.fasta     fITS7        ITS4    48956  UNITE       8.0  2019-02-12
  ITS_SINTAX   sintax    sh_general_release_dynamic_s_all_04.02.2020.fasta    ITS1-F        ITS4   139020  UNITE       8.2  2020-07-18
    ITS_UTAX     utax  sh_general_release_dynamic_all_02.02.2019_dev.fasta    ITS1-F        ITS4    50000  UNITE       8.0  2019-02-12
        test  vsearch                                           rdptest.fa      None        None       51                   2021-03-15
 test_SINTAX   sintax                                           rdptest.fa     515FB       806RB       51                   2021-03-15
   test_UTAX     utax                                           rdptest.fa     515FB       806RB       51                   2021-03-15
```

Contents of the 'DB' folder:

```20805340 Nov  9 16:46 16S.extracted.fa
   94916911 Sep 26 20:43 16S_SINTAX.udb
         65 Feb 18  2019 16S_SINTAX.udb.txt
   94916911 Feb 18  2019 16S.udb
         65 Feb 18  2019 16S.udb.txt
       6291 Nov 12 11:25 amptk_mock1.fa
      16112 Nov 12 11:25 amptk_mock2.fa
      14187 Nov 12 11:25 amptk_mock3.fa
       7918 Nov 12 11:25 amptk_synmock.fa
       4096 Mar 12 20:02 amptk_tmp_26387
    7887074 Nov 12 11:29 COI.errors.fa
 1201979958 Nov 12 11:30 COI.extracted.fa
       1681 Nov 12 11:35 COI.log
  272318560 Nov 11 17:06 COI_SINTAX.derep.extracted.fa
     883929 Nov 11 17:06 COI_SINTAX.errors.fa
          0 Nov 11 17:06 COI_SINTAX.extracted.fa
       1181 Nov 11 17:06 COI_SINTAX.log
 5011188574 Nov 12 11:35 COI.udb
         92 Nov 12 11:30 COI.udb.txt
        345 Nov 12 11:35 COI.usearch.log
   58293282 Nov 11 17:07 COI_UTAX.derep.extracted.fa
  221420695 Nov 11 17:07 COI_UTAX.errors.fa
          0 Nov 11 17:07 COI_UTAX.extracted.fa
       1249 Nov 11 17:07 COI_UTAX.log
          0 Mar 13 12:36 HSP60.errors.fa
    3643198 Mar 13 12:36 HSP60.extracted.fa
       1533 Mar 13 12:36 HSP60.log
          0 Mar 13 12:37 HSP60_SINTAX.derep.extracted.fa
    3916510 Mar 13 12:37 HSP60_SINTAX.errors.fa
          0 Mar 13 12:37 HSP60_SINTAX.extracted.fa
        650 Mar 13 12:38 HSP60_SINTAX.log
   15214440 Mar 13 12:36 HSP60.udb
         60 Mar 13 12:36 HSP60.udb.txt
        405 Mar 13 12:36 HSP60.usearch.log
          0 Mar 13 12:41 HSP.errors.fa
    3643198 Mar 13 12:41 HSP.extracted.fa
       1523 Mar 13 12:41 HSP.log
   15214440 Mar 13 12:41 HSP.udb
         60 Mar 13 12:41 HSP.udb.txt
        403 Mar 13 12:41 HSP.usearch.log
       7822 Nov 12 11:25 ioncode_barcodes.fa
       1794 Nov 12 11:25 ionxpress_barcodes.fa
  165652995 Jul 18  2020 ITS1_SINTAX.udb
         97 Jul 18  2020 ITS1_SINTAX.udb.txt
   91942748 Feb 12  2019 ITS1_UTAX.udb
         95 Feb 12  2019 ITS1_UTAX.udb.txt
  142904016 Jul 18  2020 ITS2_SINTAX.udb
         96 Jul 18  2020 ITS2_SINTAX.udb.txt
   77285213 Feb 12  2019 ITS2_UTAX.udb
         94 Feb 12  2019 ITS2_UTAX.udb.txt
  811299684 Nov  9 16:46 ITS.extracted.fa
  415750350 Jul 18  2020 ITS_SINTAX.udb
         97 Jul 18  2020 ITS_SINTAX.udb.txt
 3418051189 Jul 18  2020 ITS.udb
         83 Jul 18  2020 ITS.udb.txt
  168829739 Feb 12  2019 ITS_UTAX.udb
         95 Feb 12  2019 ITS_UTAX.udb.txt
          0 Mar 15 14:34 test.errors.fa
      80293 Mar 15 14:34 test.extracted.fa
       1494 Mar 15 14:34 test.log
          0 Mar 15 14:35 test_SINTAX.errors.fa
      19408 Mar 15 14:35 test_SINTAX.extracted.fa
       1593 Mar 15 14:35 test_SINTAX.log
        342 Mar 15 14:35 test_SINTAX.sintax.log
     331986 Mar 15 14:35 test_SINTAX.udb
         46 Mar 15 14:35 test_SINTAX.udb.txt
     630943 Mar 15 14:34 test.udb
         45 Mar 15 14:34 test.udb.txt
        338 Mar 15 14:34 test.usearch.log
          0 Mar 15 14:35 test_UTAX.errors.fa
      19408 Mar 15 14:35 test_UTAX.extracted.fa
       1805 Mar 15 14:35 test_UTAX.log
       1320 Mar 15 14:35 test_UTAX.report.txt
     341614 Mar 15 14:35 test_UTAX.udb
         44 Mar 15 14:35 test_UTAX.udb.txt
       2342 Mar 15 14:35 test_UTAX.utax.log
```

**Comment by nextgenusfs** [comment]
Okay, I see the problem in the code -- essentially I'm not loading these preconfigured databases dynamically, so that needs to be fixed in order for users to pass something like `--db test` and have it automagically get the correct databases.

So this is going to look painful, but this should work I think until I get it fixed to use the "short hand" dynamic matching of the databases, you will need to specify the path to each of the databases:
```
$ export db_location=/results/Miniconda/miniconda3/envs/amptk151/lib/python3.7/site-packages/amptk/DB
$ amptk taxonomy -f file.filtered.otus.fa -i file.final.txt -m mapping.txt -o test -m hybrid \
    --usearch_db $db_location/test.udb \
    --utax_db $db_location/test_UTAX.udb
```
And as I type this, just realized sintax_db isn't a command line option.  So I'll get this sorted, but let me know if above works or not.

**Comment by JonathanVanHamme** [comment]
Worked like a charm, Jon. Just had to change the
```
-m hybrid
```
to 

```
--method hybrid
```
in the command you suggested.

And, not at all painful, especially compared to importing Ion Torrent data into Qiime2! I am very thankful for you and AMPtk.

**Comment by nextgenusfs** [comment]
Nice, I'll push a fix to parse the databases so they can be used as you originally tried. 

Yes, nothing about Qiime2 is fun.....

**Comment by nextgenusfs** [comment]
Hi Jon, if you wouldn't mind testing you should be able to install the master from pip over the top of your existing install and let me know if working the way you would expect:
```
python -m pip install git+https://github.com/nextgenusfs/amptk.git
```
If looks good then I'll tag a new release as seems there is that other database issue #77 we fixed before that is only in master.

**Comment by JonathanVanHamme** [comment]
I installed the master from pip, but now get errors calling the custom database and the pre-installed databases using either
```
-d 16S
```
or
```
--db 16S
```

Here's an example:
```
$ amptk taxonomy -f 4110_Eric_2021Mar15.filtered.otus.fa -i 4110_Eric_2021Mar15.final.txt -m 2021Mar15_Eric_4110_AMPtkMapping_341f_806r.txt -o secondtest -d 16S
-------------------------------------------------------
[02:22:37 PM]: OS: debian buster/sid, 24 cores, ~ 396 GB RAM. Python: 3.7.8
[02:22:37 PM]: AMPtk v1.5.2, VSEARCH v2.15.1
Traceback (most recent call last):
  File "/results/Miniconda/miniconda3/envs/amptk151/bin/amptk", line 8, in <module>
    sys.exit(main())
  File "/results/Miniconda/miniconda3/envs/amptk151/lib/python3.7/site-packages/amptk/amptk.py", line 784, in main
    mod.main(arguments)
  File "/results/Miniconda/miniconda3/envs/amptk151/lib/python3.7/site-packages/amptk/assign_taxonomy.py", line 155, in main
    DataBase = parseCustomDBs(db_path, DataBase)
NameError: name 'db_path' is not defined
```

**Comment by nextgenusfs** [comment]
oh sorry, typo.  one minute.

**Comment by JonathanVanHamme** [comment]
Hmmm... getting the same errors, but I don't think the pip command updated anything - just gave me a bunch of "Requirement already satisfied" notices.

**Comment by nextgenusfs** [comment]
oh, you can add `--force --no-deps` that might make it install latest, or there is another bug.  I'll generated a custom one locally and debug.

**Comment by JonathanVanHamme** [comment]
That worked, Jon. The test database and your databases are now working perfectly. Thanks for that!
