### ISSUE TITLE
platform.linux_distribution is removed since Python 3.8

### ISSUE THREAD

**Issue by ynanyam** [nextgenusfs/amptk#91]
https://github.com/nextgenusfs/amptk/blob/067365ed7baae5b0df0d4309680469792db161e3/amptk/amptklib.py#L323

With AMPtk version 1.5.3 where python requirement is not restricted, the conda install will install the package with Python 3.9. 

> Deprecated since version 3.5, will be removed in version 3.8: See alternative like the distro package.

With Python 3.8+ AMPtk fails when following the Quick Start using the included test data

```
$ amptk illumina -i illumina_test_data -o miseq -f fITS7 -r ITS4
-------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/amptk", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/amptk/amptk.py", line 784, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.9/site-packages/amptk/process_illumina_folder.py", line 195, in main
    amptklib.SystemInfo()
  File "/usr/local/lib/python3.9/site-packages/amptk/amptklib.py", line 330, in SystemInfo
    system_os = systemOS()
  File "/usr/local/lib/python3.9/site-packages/amptk/amptklib.py", line 323, in systemOS
    linux_version = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

--
Yash

**Comment by hyphaltip** [comment]
@nextgenusfs and I were working on a solution to this in Oct - I don't think we had finish fixing it though, I had just downgraded python to 3.7 in the conda env for the time being.
